version: '3'

services:
  backend:
    build:
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    command: "npm run dev"
    env_file:
      - backend/.env
