version: '3'

services:
  backend:
    build:
      dockerfile: ./docker/backend/Dockerfile
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    command: "npm run prisma:generate && npm run dev"
    env_file:
      - backend/.env
    depends_on:
      - mysql

  parsers:
    build:
      dockerfile: ./docker/parsers/Dockerfile
    restart: always
    volumes:
      - ./parsers:/app
    command: "npm run start"

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
