version: '3'

services:
  frontend:
    build:
      dockerfile: ./docker/prod/frontend/Dockerfile
      context: ./
    restart: always
    volumes:
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "80:3000"
    command: >
      sh -c " npm install &&  
              npm i serve -g &&
              serve -s build"

  admin:
    build:
      dockerfile: ./docker/prod/admin/Dockerfile
      context: ./
    restart: always
    ports:
      - "8081:5000"
    command: >
      sh -c "npm install &&  
                npm run start"

  backend:
    build:
      dockerfile: ./docker/prod/backend/Dockerfile
      context: ./
    restart: always
    volumes:
      - ./backend/node_modules:/app/node_modules
    ports:
      - '3000:3000'
    command: >
      sh -c " npm install &&  
              npm run start"
    env_file:
      - backend/.env
    depends_on:
      - mysql

  parsers:
    build:
      dockerfile: ./docker/prod/parsers/Dockerfile
      context: ./
    restart: always
    volumes:
      - ./parsers/src:/app/src
      - ./parsers/package.json:/app/package.json
    command: >
      sh -c " npm install &&  
              npm run start"


  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
