version: '3'
services:
    nodejs:
        build:
            context: '/backend'
        volumes:
            - './backend:/backend'
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
        depends_on:
            - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - TELEGRAM_BOT_TOKEN=5876569500:AAFeV1z_aUkffugJo7Ij7L_amkH3mZjRc9E
            - TELEGRAM_CHANNEL_ID=-1001769175610

    nginx:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - './frontend/build:/usr/share/nginx/html'

    mysql:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_DATABASE=$MYSQL_DATABASE
        container_name: mysql
        ports:
            - '3306:3306'
